import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My program",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>)
{
    return (
        <html lang="en">
        <body className={`${inter.className} bg-black text-white`}>
        <header className="flex justify-between items-center bg-white text-black p-4">
            <h1 className="text-center">My page</h1>
            <div className="text-right">
                <p>For contact: 119762@student.san.edu.pl</p>
            </div>
        </header>
        {children}
        <footer className="fixed bottom-0 right-0 p-4">
            <span className="mr-4 text-black">My social medias:</span>
            <div className="flex space-x-4">
                <a href="https://www.facebook.com/nazar.viniarskyi" target="_blank" rel="noopener noreferrer">
                    <Image src="/facebook.svg" alt="Facebook Logo" width={24} height={24}/>
                </a>
                <a href="https://www.instagram.com/boy.broke.af/" target="_blank" rel="noopener noreferrer">
                    <Image src="/instagram.svg" alt="Instagram Logo" width={24} height={24}/>
                </a>
                <a href="https://twitter.com/Quandel84754585" target="_blank" rel="noopener noreferrer">
                    <Image src="/twitter.svg" alt="Twitter Logo" width={24} height={24}/>
                </a>
            </div>
        </footer>
        </body>
        </html>
    );
}